DROP TABLE IF EXISTS LINEITEM CASCADE;
DROP TABLE IF EXISTS ORDERS CASCADE;
DROP TABLE IF EXISTS PARTSUPP CASCADE;
DROP TABLE IF EXISTS PART CASCADE;
DROP TABLE IF EXISTS SUPPLIER CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS NATION CASCADE;
DROP TABLE IF EXISTS REGION CASCADE;
